version: '3'

services:
  web:
    image: python:3.11
    command: bash -c "pip install -r requirements.txt && python app.py"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    working_dir: /app
