version: '3'
services:
  web:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000