version: '3'
services:
  myapi:
    image: python:3.11
    volumes:
      - .C:\Users\tiepp\Documentos\ESPM\DevOps\projeto\projectF:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python main.py"
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
